sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    packages:
      - libgsl0-dev
      - libhdf5-serial-dev
      - libcunit1-dev
      - python-h5py
      - graphviz
      - doxygen

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  # Install newer version of pip to take advantage of bdist_wheel cache.
  - pip install pip --upgrade
  # We install these requirements here rather than through the requirements.txt
  # file because of issues on readthedocs. First we install Cython so that it
  # creates a bdist_wheel and then h5py. This allows Travis to cache the builds.
  - pip install Cython
  - pip install h5py
  - pip install -r requirements.txt
  - CFLAGS=--coverage python setup.py build_ext --inplace

script:
  - flake8 --max-line-length 89 setup.py msprime tests
  - nosetests -v --with-coverage --cover-package msprime
      --cover-branches --cover-erase --cover-xml
      --cover-inclusive --cover-min-percentage 90 tests
  # Only make the docs on a recent version of Python to avoid problems with Sphinx.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then make -C docs; fi
  # Make sure we can install successfully.
  - python setup.py sdist
  - pip install dist/msprime*.tar.gz --no-cache-dir
  # Now run the low-level tests.
  - make -C lib travis-tests
  - ./lib/tests 
  - cd docs/ && doxygen > /dev/null && cd ..

after_success:
  # Run gcov manually, as the one used in codecov doesn't work here.
  - gcov -pb -o ./build/temp.linux*/ _msprimemodule.c
  - find ./lib -type f -name '*.gcno' -exec gcov -pb -o ./lib {} +
  - codecov -X gcov
